package me.witherbuilder13.a_world_reimagined.block.util;

import com.google.common.collect.Maps;
import me.witherbuilder13.a_world_reimagined.block.AWRBlocks;
import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.data.BlockFamily;
import net.minecraft.world.level.block.Block;

import java.util.Map;
import java.util.stream.Stream;

import static me.witherbuilder13.a_world_reimagined.block.AWRBlocks.*;

public class AWRBlockFamilies {
    
    private static final Map<Block, BlockFamily> MAP = Maps.newHashMap();
    private static final String RECIPE_GROUP_PREFIX_WOODEN = "wooden";
    private static final String RECIPE_UNLOCKED_BY_HAS_PLANKS = "has_planks";
    
    
    public static final BlockFamily ALDER = familyBuilder(ALDER_PLANKS)
            .log(ALDER_LOG)
            .strippedLog(STRIPPED_ALDER_LOG)
            .stairs(ALDER_STAIRS)
            .slab(ALDER_SLAB)
            .fence(ALDER_FENCE)
            .fenceGate(ALDER_FENCE_GATE)
            .door(ALDER_DOOR)
            .trapdoor(ALDER_TRAPDOOR)
            .pressurePlate(ALDER_PRESSURE_PLATE)
            .button(ALDER_BUTTON)
            .sign(ALDER_SIGN, ALDER_WALL_SIGN)
            .hangingSign(ALDER_HANGING_SIGN, ALDER_WALL_HANGING_SIGN)
            .recipeGroupPrefix(RECIPE_GROUP_PREFIX_WOODEN)
            .recipeUnlockedBy(RECIPE_UNLOCKED_BY_HAS_PLANKS)
            .getFamily();
    
    public static final BlockFamily APPLE = familyBuilder(APPLE_PLANKS)
            .log(APPLE_LOG)
            .strippedLog(STRIPPED_APPLE_LOG)
            .stairs(APPLE_STAIRS)
            .slab(APPLE_SLAB)
            .fence(APPLE_FENCE)
            .fenceGate(APPLE_FENCE_GATE)
            .door(APPLE_DOOR)
            .trapdoor(APPLE_TRAPDOOR)
            .pressurePlate(APPLE_PRESSURE_PLATE)
            .button(APPLE_BUTTON)
            .sign(APPLE_SIGN, APPLE_WALL_SIGN)
            .hangingSign(APPLE_HANGING_SIGN, APPLE_WALL_HANGING_SIGN)
            .recipeGroupPrefix(RECIPE_GROUP_PREFIX_WOODEN)
            .recipeUnlockedBy(RECIPE_UNLOCKED_BY_HAS_PLANKS)
            .getFamily();
    
    public static final BlockFamily ASPEN = familyBuilder(ASPEN_PLANKS)
            .log(ASPEN_LOG)
            .strippedLog(STRIPPED_ASPEN_LOG)
            .stairs(ASPEN_STAIRS)
            .slab(ASPEN_SLAB)
            .fence(ASPEN_FENCE)
            .fenceGate(ASPEN_FENCE_GATE)
            .door(ASPEN_DOOR)
            .trapdoor(ASPEN_TRAPDOOR)
            .pressurePlate(ASPEN_PRESSURE_PLATE)
            .button(ASPEN_BUTTON)
            .sign(ASPEN_SIGN, ASPEN_WALL_SIGN)
            .hangingSign(ASPEN_HANGING_SIGN, ASPEN_WALL_HANGING_SIGN)
            .recipeGroupPrefix(RECIPE_GROUP_PREFIX_WOODEN)
            .recipeUnlockedBy(RECIPE_UNLOCKED_BY_HAS_PLANKS)
            .getFamily();
    
    public static final BlockFamily BAOBAB = familyBuilder(BAOBAB_PLANKS)
            .log(BAOBAB_LOG)
            .strippedLog(STRIPPED_BAOBAB_LOG)
            .stairs(BAOBAB_STAIRS)
            .slab(BAOBAB_SLAB)
            .fence(BAOBAB_FENCE)
            .fenceGate(BAOBAB_FENCE_GATE)
            .door(BAOBAB_DOOR)
            .trapdoor(BAOBAB_TRAPDOOR)
            .pressurePlate(BAOBAB_PRESSURE_PLATE)
            .button(BAOBAB_BUTTON)
            .sign(BAOBAB_SIGN, BAOBAB_WALL_SIGN)
            .hangingSign(BAOBAB_HANGING_SIGN, BAOBAB_WALL_HANGING_SIGN)
            .recipeGroupPrefix(RECIPE_GROUP_PREFIX_WOODEN)
            .recipeUnlockedBy(RECIPE_UNLOCKED_BY_HAS_PLANKS)
            .getFamily();
    
    public static final BlockFamily BEECH = familyBuilder(BEECH_PLANKS)
            .log(BEECH_LOG)
            .strippedLog(STRIPPED_BEECH_LOG)
            .stairs(BEECH_STAIRS)
            .slab(BEECH_SLAB)
            .fence(BEECH_FENCE)
            .fenceGate(BEECH_FENCE_GATE)
            .door(BEECH_DOOR)
            .trapdoor(BEECH_TRAPDOOR)
            .pressurePlate(BEECH_PRESSURE_PLATE)
            .button(BEECH_BUTTON)
            .sign(BEECH_SIGN, BEECH_WALL_SIGN)
            .hangingSign(BEECH_HANGING_SIGN, BEECH_WALL_HANGING_SIGN)
            .recipeGroupPrefix(RECIPE_GROUP_PREFIX_WOODEN)
            .recipeUnlockedBy(RECIPE_UNLOCKED_BY_HAS_PLANKS)
            .getFamily();

    public static final BlockFamily CEDAR = familyBuilder(CEDAR_PLANKS)
            .log(CEDAR_LOG)
            .strippedLog(STRIPPED_CEDAR_LOG)
            .stairs(CEDAR_STAIRS)
            .slab(CEDAR_SLAB)
            .fence(CEDAR_FENCE)
            .fenceGate(CEDAR_FENCE_GATE)
            .door(CEDAR_DOOR)
            .trapdoor(CEDAR_TRAPDOOR)
            .pressurePlate(CEDAR_PRESSURE_PLATE)
            .button(CEDAR_BUTTON)
            .sign(CEDAR_SIGN, CEDAR_WALL_SIGN)
            .hangingSign(CEDAR_HANGING_SIGN, CEDAR_WALL_HANGING_SIGN)
            .recipeGroupPrefix(RECIPE_GROUP_PREFIX_WOODEN)
            .recipeUnlockedBy(RECIPE_UNLOCKED_BY_HAS_PLANKS)
            .getFamily();
    
    public static final BlockFamily CHERRY = familyBuilder(CHERRY_PLANKS)
            .log(CHERRY_LOG)
            .strippedLog(STRIPPED_CHERRY_LOG)
            .stairs(CHERRY_STAIRS)
            .slab(CHERRY_SLAB)
            .fence(CHERRY_FENCE)
            .fenceGate(CHERRY_FENCE_GATE)
            .door(CHERRY_DOOR)
            .trapdoor(CHERRY_TRAPDOOR)
            .pressurePlate(CHERRY_PRESSURE_PLATE)
            .button(CHERRY_BUTTON)
            .sign(CHERRY_SIGN, CHERRY_WALL_SIGN)
            .hangingSign(CHERRY_HANGING_SIGN, CHERRY_WALL_HANGING_SIGN)
            .recipeGroupPrefix(RECIPE_GROUP_PREFIX_WOODEN)
            .recipeUnlockedBy(RECIPE_UNLOCKED_BY_HAS_PLANKS)
            .getFamily();
    
    public static final BlockFamily CYPRESS = familyBuilder(CYPRESS_PLANKS)
            .log(CYPRESS_LOG)
            .strippedLog(STRIPPED_CYPRESS_LOG)
            .stairs(CYPRESS_STAIRS)
            .slab(CYPRESS_SLAB)
            .fence(CYPRESS_FENCE)
            .fenceGate(CYPRESS_FENCE_GATE)
            .door(CYPRESS_DOOR)
            .trapdoor(CYPRESS_TRAPDOOR)
            .pressurePlate(CYPRESS_PRESSURE_PLATE)
            .button(CYPRESS_BUTTON)
            .sign(CYPRESS_SIGN, CYPRESS_WALL_SIGN)
            .hangingSign(CYPRESS_HANGING_SIGN, CYPRESS_WALL_HANGING_SIGN)
            .recipeGroupPrefix(RECIPE_GROUP_PREFIX_WOODEN)
            .recipeUnlockedBy(RECIPE_UNLOCKED_BY_HAS_PLANKS)
            .getFamily();
    
    public static final BlockFamily EBONY = familyBuilder(EBONY_PLANKS)
            .log(EBONY_LOG)
            .strippedLog(STRIPPED_EBONY_LOG)
            .stairs(EBONY_STAIRS)
            .slab(EBONY_SLAB)
            .fence(EBONY_FENCE)
            .fenceGate(EBONY_FENCE_GATE)
            .door(EBONY_DOOR)
            .trapdoor(EBONY_TRAPDOOR)
            .pressurePlate(EBONY_PRESSURE_PLATE)
            .button(EBONY_BUTTON)
            .sign(EBONY_SIGN, EBONY_WALL_SIGN)
            .hangingSign(EBONY_HANGING_SIGN, EBONY_WALL_HANGING_SIGN)
            .recipeGroupPrefix(RECIPE_GROUP_PREFIX_WOODEN)
            .recipeUnlockedBy(RECIPE_UNLOCKED_BY_HAS_PLANKS)
            .getFamily();
    
    public static final BlockFamily ELM = familyBuilder(ELM_PLANKS)
            .log(ELM_LOG)
            .strippedLog(STRIPPED_ELM_LOG)
            .stairs(ELM_STAIRS)
            .slab(ELM_SLAB)
            .fence(ELM_FENCE)
            .fenceGate(ELM_FENCE_GATE)
            .door(ELM_DOOR)
            .trapdoor(ELM_TRAPDOOR)
            .pressurePlate(ELM_PRESSURE_PLATE)
            .button(ELM_BUTTON)
            .sign(ELM_SIGN, ELM_WALL_SIGN)
            .hangingSign(ELM_HANGING_SIGN, ELM_WALL_HANGING_SIGN)
            .recipeGroupPrefix(RECIPE_GROUP_PREFIX_WOODEN)
            .recipeUnlockedBy(RECIPE_UNLOCKED_BY_HAS_PLANKS)
            .getFamily();
    
    public static final BlockFamily EUCALYPTUS = familyBuilder(EUCALYPTUS_PLANKS)
            .log(EUCALYPTUS_LOG)
            .strippedLog(STRIPPED_EUCALYPTUS_LOG)
            .stairs(EUCALYPTUS_STAIRS)
            .slab(EUCALYPTUS_SLAB)
            .fence(EUCALYPTUS_FENCE)
            .fenceGate(EUCALYPTUS_FENCE_GATE)
            .door(EUCALYPTUS_DOOR)
            .trapdoor(EUCALYPTUS_TRAPDOOR)
            .pressurePlate(EUCALYPTUS_PRESSURE_PLATE)
            .button(EUCALYPTUS_BUTTON)
            .sign(EUCALYPTUS_SIGN, EUCALYPTUS_WALL_SIGN)
            .hangingSign(EUCALYPTUS_HANGING_SIGN, EUCALYPTUS_WALL_HANGING_SIGN)
            .recipeGroupPrefix(RECIPE_GROUP_PREFIX_WOODEN)
            .recipeUnlockedBy(RECIPE_UNLOCKED_BY_HAS_PLANKS)
            .getFamily();
    
    public static final BlockFamily FIG = familyBuilder(FIG_PLANKS)
            .log(FIG_LOG)
            .strippedLog(STRIPPED_FIG_LOG)
            .stairs(FIG_STAIRS)
            .slab(FIG_SLAB)
            .fence(FIG_FENCE)
            .fenceGate(FIG_FENCE_GATE)
            .door(FIG_DOOR)
            .trapdoor(FIG_TRAPDOOR)
            .pressurePlate(FIG_PRESSURE_PLATE)
            .button(FIG_BUTTON)
            .sign(FIG_SIGN, FIG_WALL_SIGN)
            .hangingSign(FIG_HANGING_SIGN, FIG_WALL_HANGING_SIGN)
            .recipeGroupPrefix(RECIPE_GROUP_PREFIX_WOODEN)
            .recipeUnlockedBy(RECIPE_UNLOCKED_BY_HAS_PLANKS)
            .getFamily();

    public static final BlockFamily FIR = familyBuilder(FIR_PLANKS)
            .log(FIR_LOG)
            .strippedLog(STRIPPED_FIR_LOG)
            .stairs(FIR_STAIRS)
            .slab(FIR_SLAB)
            .fence(FIR_FENCE)
            .fenceGate(FIR_FENCE_GATE)
            .door(FIR_DOOR)
            .trapdoor(FIR_TRAPDOOR)
            .pressurePlate(FIR_PRESSURE_PLATE)
            .button(FIR_BUTTON)
            .sign(FIR_SIGN, FIR_WALL_SIGN)
            .hangingSign(FIR_HANGING_SIGN, FIR_WALL_HANGING_SIGN)
            .recipeGroupPrefix(RECIPE_GROUP_PREFIX_WOODEN)
            .recipeUnlockedBy(RECIPE_UNLOCKED_BY_HAS_PLANKS)
            .getFamily();

    public static final BlockFamily HEMLOCK = familyBuilder(HEMLOCK_PLANKS)
            .log(HEMLOCK_LOG)
            .strippedLog(STRIPPED_HEMLOCK_LOG)
            .stairs(HEMLOCK_STAIRS)
            .slab(HEMLOCK_SLAB)
            .fence(HEMLOCK_FENCE)
            .fenceGate(HEMLOCK_FENCE_GATE)
            .door(HEMLOCK_DOOR)
            .trapdoor(HEMLOCK_TRAPDOOR)
            .pressurePlate(HEMLOCK_PRESSURE_PLATE)
            .button(HEMLOCK_BUTTON)
            .sign(HEMLOCK_SIGN, HEMLOCK_WALL_SIGN)
            .hangingSign(HEMLOCK_HANGING_SIGN, HEMLOCK_WALL_HANGING_SIGN)
            .recipeGroupPrefix(RECIPE_GROUP_PREFIX_WOODEN)
            .recipeUnlockedBy(RECIPE_UNLOCKED_BY_HAS_PLANKS)
            .getFamily();
    
    public static final BlockFamily HICKORY = familyBuilder(HICKORY_PLANKS)
            .log(HICKORY_LOG)
            .strippedLog(STRIPPED_HICKORY_LOG)
            .stairs(HICKORY_STAIRS)
            .slab(HICKORY_SLAB)
            .fence(HICKORY_FENCE)
            .fenceGate(HICKORY_FENCE_GATE)
            .door(HICKORY_DOOR)
            .trapdoor(HICKORY_TRAPDOOR)
            .pressurePlate(HICKORY_PRESSURE_PLATE)
            .button(HICKORY_BUTTON)
            .sign(HICKORY_SIGN, HICKORY_WALL_SIGN)
            .hangingSign(HICKORY_HANGING_SIGN, HICKORY_WALL_HANGING_SIGN)
            .recipeGroupPrefix(RECIPE_GROUP_PREFIX_WOODEN)
            .recipeUnlockedBy(RECIPE_UNLOCKED_BY_HAS_PLANKS)
            .getFamily();
    
    public static final BlockFamily JUNIPER = familyBuilder(JUNIPER_PLANKS)
            .log(JUNIPER_LOG)
            .strippedLog(STRIPPED_JUNIPER_LOG)
            .stairs(JUNIPER_STAIRS)
            .slab(JUNIPER_SLAB)
            .fence(JUNIPER_FENCE)
            .fenceGate(JUNIPER_FENCE_GATE)
            .door(JUNIPER_DOOR)
            .trapdoor(JUNIPER_TRAPDOOR)
            .pressurePlate(JUNIPER_PRESSURE_PLATE)
            .button(JUNIPER_BUTTON)
            .sign(JUNIPER_SIGN, JUNIPER_WALL_SIGN)
            .hangingSign(JUNIPER_HANGING_SIGN, JUNIPER_WALL_HANGING_SIGN)
            .recipeGroupPrefix(RECIPE_GROUP_PREFIX_WOODEN)
            .recipeUnlockedBy(RECIPE_UNLOCKED_BY_HAS_PLANKS)
            .getFamily();
    
    public static final BlockFamily KAPOK = familyBuilder(KAPOK_PLANKS)
            .log(KAPOK_LOG)
            .strippedLog(STRIPPED_KAPOK_LOG)
            .stairs(KAPOK_STAIRS)
            .slab(KAPOK_SLAB)
            .fence(KAPOK_FENCE)
            .fenceGate(KAPOK_FENCE_GATE)
            .door(KAPOK_DOOR)
            .trapdoor(KAPOK_TRAPDOOR)
            .pressurePlate(KAPOK_PRESSURE_PLATE)
            .button(KAPOK_BUTTON)
            .sign(KAPOK_SIGN, KAPOK_WALL_SIGN)
            .hangingSign(KAPOK_HANGING_SIGN, KAPOK_WALL_HANGING_SIGN)
            .recipeGroupPrefix(RECIPE_GROUP_PREFIX_WOODEN)
            .recipeUnlockedBy(RECIPE_UNLOCKED_BY_HAS_PLANKS)
            .getFamily();

    public static final BlockFamily LARCH = familyBuilder(LARCH_PLANKS)
            .log(LARCH_LOG)
            .strippedLog(STRIPPED_LARCH_LOG)
            .stairs(LARCH_STAIRS)
            .slab(LARCH_SLAB)
            .fence(LARCH_FENCE)
            .fenceGate(LARCH_FENCE_GATE)
            .door(LARCH_DOOR)
            .trapdoor(LARCH_TRAPDOOR)
            .pressurePlate(LARCH_PRESSURE_PLATE)
            .button(LARCH_BUTTON)
            .sign(LARCH_SIGN, LARCH_WALL_SIGN)
            .hangingSign(LARCH_HANGING_SIGN, LARCH_WALL_HANGING_SIGN)
            .recipeGroupPrefix(RECIPE_GROUP_PREFIX_WOODEN)
            .recipeUnlockedBy(RECIPE_UNLOCKED_BY_HAS_PLANKS)
            .getFamily();
    
    public static final BlockFamily MAHOGANY = familyBuilder(MAHOGANY_PLANKS)
            .log(MAHOGANY_LOG)
            .strippedLog(STRIPPED_MAHOGANY_LOG)
            .stairs(MAHOGANY_STAIRS)
            .slab(MAHOGANY_SLAB)
            .fence(MAHOGANY_FENCE)
            .fenceGate(MAHOGANY_FENCE_GATE)
            .door(MAHOGANY_DOOR)
            .trapdoor(MAHOGANY_TRAPDOOR)
            .pressurePlate(MAHOGANY_PRESSURE_PLATE)
            .button(MAHOGANY_BUTTON)
            .sign(MAHOGANY_SIGN, MAHOGANY_WALL_SIGN)
            .hangingSign(MAHOGANY_HANGING_SIGN, MAHOGANY_WALL_HANGING_SIGN)
            .recipeGroupPrefix(RECIPE_GROUP_PREFIX_WOODEN)
            .recipeUnlockedBy(RECIPE_UNLOCKED_BY_HAS_PLANKS)
            .getFamily();
    
    public static final BlockFamily MAPLE = familyBuilder(MAPLE_PLANKS)
            .log(MAPLE_LOG)
            .strippedLog(STRIPPED_MAPLE_LOG)
            .stairs(MAPLE_STAIRS)
            .slab(MAPLE_SLAB)
            .fence(MAPLE_FENCE)
            .fenceGate(MAPLE_FENCE_GATE)
            .door(MAPLE_DOOR)
            .trapdoor(MAPLE_TRAPDOOR)
            .pressurePlate(MAPLE_PRESSURE_PLATE)
            .button(MAPLE_BUTTON)
            .sign(MAPLE_SIGN, MAPLE_WALL_SIGN)
            .hangingSign(MAPLE_HANGING_SIGN, MAPLE_WALL_HANGING_SIGN)
            .recipeGroupPrefix(RECIPE_GROUP_PREFIX_WOODEN)
            .recipeUnlockedBy(RECIPE_UNLOCKED_BY_HAS_PLANKS)
            .getFamily();
    
    public static final BlockFamily MESQUITE = familyBuilder(MESQUITE_PLANKS)
            .log(MESQUITE_LOG)
            .strippedLog(STRIPPED_MESQUITE_LOG)
            .stairs(MESQUITE_STAIRS)
            .slab(MESQUITE_SLAB)
            .fence(MESQUITE_FENCE)
            .fenceGate(MESQUITE_FENCE_GATE)
            .door(MESQUITE_DOOR)
            .trapdoor(MESQUITE_TRAPDOOR)
            .pressurePlate(MESQUITE_PRESSURE_PLATE)
            .button(MESQUITE_BUTTON)
            .sign(MESQUITE_SIGN, MESQUITE_WALL_SIGN)
            .hangingSign(MESQUITE_HANGING_SIGN, MESQUITE_WALL_HANGING_SIGN)
            .recipeGroupPrefix(RECIPE_GROUP_PREFIX_WOODEN)
            .recipeUnlockedBy(RECIPE_UNLOCKED_BY_HAS_PLANKS)
            .getFamily();
    
    public static final BlockFamily OLIVE = familyBuilder(OLIVE_PLANKS)
            .log(OLIVE_LOG)
            .strippedLog(STRIPPED_OLIVE_LOG)
            .stairs(OLIVE_STAIRS)
            .slab(OLIVE_SLAB)
            .fence(OLIVE_FENCE)
            .fenceGate(OLIVE_FENCE_GATE)
            .door(OLIVE_DOOR)
            .trapdoor(OLIVE_TRAPDOOR)
            .pressurePlate(OLIVE_PRESSURE_PLATE)
            .button(OLIVE_BUTTON)
            .sign(OLIVE_SIGN, OLIVE_WALL_SIGN)
            .hangingSign(OLIVE_HANGING_SIGN, OLIVE_WALL_HANGING_SIGN)
            .recipeGroupPrefix(RECIPE_GROUP_PREFIX_WOODEN)
            .recipeUnlockedBy(RECIPE_UNLOCKED_BY_HAS_PLANKS)
            .getFamily();
    
    public static final BlockFamily PALM = familyBuilder(PALM_PLANKS)
            .log(PALM_LOG)
            .strippedLog(STRIPPED_PALM_LOG)
            .stairs(PALM_STAIRS)
            .slab(PALM_SLAB)
            .fence(PALM_FENCE)
            .fenceGate(PALM_FENCE_GATE)
            .door(PALM_DOOR)
            .trapdoor(PALM_TRAPDOOR)
            .pressurePlate(PALM_PRESSURE_PLATE)
            .button(PALM_BUTTON)
            .sign(PALM_SIGN, PALM_WALL_SIGN)
            .hangingSign(PALM_HANGING_SIGN, PALM_WALL_HANGING_SIGN)
            .recipeGroupPrefix(RECIPE_GROUP_PREFIX_WOODEN)
            .recipeUnlockedBy(RECIPE_UNLOCKED_BY_HAS_PLANKS)
            .getFamily();
    
    public static final BlockFamily PALO_VERDE = familyBuilder(PALO_VERDE_PLANKS)
            .log(PALO_VERDE_LOG)
            .strippedLog(STRIPPED_PALO_VERDE_LOG)
            .stairs(PALO_VERDE_STAIRS)
            .slab(PALO_VERDE_SLAB)
            .fence(PALO_VERDE_FENCE)
            .fenceGate(PALO_VERDE_FENCE_GATE)
            .door(PALO_VERDE_DOOR)
            .trapdoor(PALO_VERDE_TRAPDOOR)
            .pressurePlate(PALO_VERDE_PRESSURE_PLATE)
            .button(PALO_VERDE_BUTTON)
            .sign(PALO_VERDE_SIGN, PALO_VERDE_WALL_SIGN)
            .hangingSign(PALO_VERDE_HANGING_SIGN, PALO_VERDE_WALL_HANGING_SIGN)
            .recipeGroupPrefix(RECIPE_GROUP_PREFIX_WOODEN)
            .recipeUnlockedBy(RECIPE_UNLOCKED_BY_HAS_PLANKS)
            .getFamily();

    public static final BlockFamily PINE = familyBuilder(PINE_PLANKS)
            .log(PINE_LOG)
            .strippedLog(STRIPPED_PINE_LOG)
            .stairs(PINE_STAIRS)
            .slab(PINE_SLAB)
            .fence(PINE_FENCE)
            .fenceGate(PINE_FENCE_GATE)
            .door(PINE_DOOR)
            .trapdoor(PINE_TRAPDOOR)
            .pressurePlate(PINE_PRESSURE_PLATE)
            .button(PINE_BUTTON)
            .sign(PINE_SIGN, PINE_WALL_SIGN)
            .hangingSign(PINE_HANGING_SIGN, PINE_WALL_HANGING_SIGN)
            .recipeGroupPrefix(RECIPE_GROUP_PREFIX_WOODEN)
            .recipeUnlockedBy(RECIPE_UNLOCKED_BY_HAS_PLANKS)
            .getFamily();

    public static final BlockFamily REDWOOD = familyBuilder(REDWOOD_PLANKS)
            .log(REDWOOD_LOG)
            .strippedLog(STRIPPED_REDWOOD_LOG)
            .stairs(REDWOOD_STAIRS)
            .slab(REDWOOD_SLAB)
            .fence(REDWOOD_FENCE)
            .fenceGate(REDWOOD_FENCE_GATE)
            .door(REDWOOD_DOOR)
            .trapdoor(REDWOOD_TRAPDOOR)
            .pressurePlate(REDWOOD_PRESSURE_PLATE)
            .button(REDWOOD_BUTTON)
            .sign(REDWOOD_SIGN, REDWOOD_WALL_SIGN)
            .hangingSign(REDWOOD_HANGING_SIGN, REDWOOD_WALL_HANGING_SIGN)
            .recipeGroupPrefix(RECIPE_GROUP_PREFIX_WOODEN)
            .recipeUnlockedBy(RECIPE_UNLOCKED_BY_HAS_PLANKS)
            .getFamily();

    public static final BlockFamily SEQUOIA = familyBuilder(SEQUOIA_PLANKS)
            .log(SEQUOIA_LOG)
            .strippedLog(STRIPPED_SEQUOIA_LOG)
            .stairs(SEQUOIA_STAIRS)
            .slab(SEQUOIA_SLAB)
            .fence(SEQUOIA_FENCE)
            .fenceGate(SEQUOIA_FENCE_GATE)
            .door(SEQUOIA_DOOR)
            .trapdoor(SEQUOIA_TRAPDOOR)
            .pressurePlate(SEQUOIA_PRESSURE_PLATE)
            .button(SEQUOIA_BUTTON)
            .sign(SEQUOIA_SIGN, SEQUOIA_WALL_SIGN)
            .hangingSign(SEQUOIA_HANGING_SIGN, SEQUOIA_WALL_HANGING_SIGN)
            .recipeGroupPrefix(RECIPE_GROUP_PREFIX_WOODEN)
            .recipeUnlockedBy(RECIPE_UNLOCKED_BY_HAS_PLANKS)
            .getFamily();
    
    public static final BlockFamily WILLOW = familyBuilder(WILLOW_PLANKS)
            .log(WILLOW_LOG)
            .strippedLog(STRIPPED_WILLOW_LOG)
            .stairs(WILLOW_STAIRS)
            .slab(WILLOW_SLAB)
            .fence(WILLOW_FENCE)
            .fenceGate(WILLOW_FENCE_GATE)
            .door(WILLOW_DOOR)
            .trapdoor(WILLOW_TRAPDOOR)
            .pressurePlate(WILLOW_PRESSURE_PLATE)
            .button(WILLOW_BUTTON)
            .sign(WILLOW_SIGN, WILLOW_WALL_SIGN)
            .hangingSign(WILLOW_HANGING_SIGN, WILLOW_WALL_HANGING_SIGN)
            .recipeGroupPrefix(RECIPE_GROUP_PREFIX_WOODEN)
            .recipeUnlockedBy(RECIPE_UNLOCKED_BY_HAS_PLANKS)
            .getFamily();
    
    //* ----------------------------------------------------------------------------------------------------------------

    public static final BlockFamily WHITE_SANDSTONE = familyBuilder(AWRBlocks.WHITE_SANDSTONE)
            .stairs(WHITE_SANDSTONE_STAIRS)
            .slab(WHITE_SANDSTONE_SLAB)
            .wall(WHITE_SANDSTONE_WALL)
            .cut(AWRBlocks.CUT_WHITE_SANDSTONE)
            .chiseled(CHISELED_WHITE_SANDSTONE)
            .dontGenerateCraftingRecipe()
            .generateStonecutterRecipe()
            .getFamily();

    public static final BlockFamily CUT_WHITE_SANDSTONE = familyBuilder(AWRBlocks.CUT_WHITE_SANDSTONE)
            .slab(CUT_WHITE_SANDSTONE_SLAB)
            .generateStonecutterRecipe()
            .getFamily();

    public static final BlockFamily SMOOTH_WHITE_SANDSTONE = familyBuilder(AWRBlocks.SMOOTH_WHITE_SANDSTONE)
            .stairs(SMOOTH_WHITE_SANDSTONE_STAIRS)
            .slab(SMOOTH_WHITE_SANDSTONE_SLAB)
            .generateStonecutterRecipe()
            .getFamily();
    
    public static final BlockFamily SNOW_BRICK = familyBuilder(SNOW_BRICKS)
            .stairs(SNOW_BRICK_STAIRS)
            .slab(SNOW_BRICK_SLAB)
            .wall(SNOW_BRICK_WALL)
            .generateStonecutterRecipe()
            .getFamily();
    
    public static final BlockFamily PACKED_ICE_BRICK = familyBuilder(PACKED_ICE_BRICKS)
            .stairs(PACKED_ICE_BRICK_STAIRS)
            .slab(PACKED_ICE_BRICK_SLAB)
            .wall(PACKED_ICE_BRICK_WALL)
            .generateStonecutterRecipe()
            .getFamily();

    //` -------------------------------------------------------------------------------------------------------------------------
    
    public static BlockFamily.Builder familyBuilder(final Block base) {
        BlockFamily.Builder builder = new BlockFamily.Builder(base);
        BlockFamily blockFamily = MAP.put(base, builder.getFamily());
        if (blockFamily != null) {
            throw new IllegalStateException("Duplicate family definition for " + BuiltInRegistries.BLOCK.getKey(base));
        } else {
            return builder;
        }
    }
    
    public static Stream<BlockFamily> getAllFamilies() {
        return MAP.values().stream();
    }

    public static void init() {}
}
