package me.witherbuilder13.a_world_reimagined.datagen;

import me.witherbuilder13.a_world_reimagined.block.FruitLeavesBlock;
import me.witherbuilder13.a_world_reimagined.item.AWRItems;
import net.fabricmc.fabric.api.datagen.v1.FabricPackOutput;
import net.fabricmc.fabric.api.datagen.v1.provider.FabricBlockLootSubProvider;
import net.minecraft.advancements.predicates.StatePropertiesPredicate;
import net.minecraft.core.HolderLookup;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.Items;
import net.minecraft.world.level.block.Block;
import net.minecraft.world.level.block.DoublePlantBlock;
import net.minecraft.world.level.block.SnowLayerBlock;
import net.minecraft.world.level.block.state.properties.DoubleBlockHalf;
import net.minecraft.world.level.storage.loot.LootContext;
import net.minecraft.world.level.storage.loot.LootPool;
import net.minecraft.world.level.storage.loot.LootTable;
import net.minecraft.world.level.storage.loot.entries.AlternativesEntry;
import net.minecraft.world.level.storage.loot.entries.LootItem;
import net.minecraft.world.level.storage.loot.functions.SetItemCountFunction;
import net.minecraft.world.level.storage.loot.predicates.LootItemEntityPropertyCondition;
import net.minecraft.world.level.storage.loot.predicates.MatchBlock;
import net.minecraft.world.level.storage.loot.providers.number.ints.ContextIntProviders;

import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.concurrent.CompletableFuture;

import static me.witherbuilder13.a_world_reimagined.block.AWRBlocks.*;
import static net.minecraft.world.level.block.Blocks.DIRT;

public class AWRBlockLootProvider extends FabricBlockLootSubProvider {
	
	protected AWRBlockLootProvider(FabricPackOutput packOutput, CompletableFuture<HolderLookup.Provider> registriesFuture) {
		super(packOutput, registriesFuture);
	}
	
	@Override
	public void generate() {
		
		List<Block> dropSelfBlocks = List.of(
				
				ALDER_LOG, ALDER_WOOD, STRIPPED_ALDER_LOG, STRIPPED_ALDER_WOOD, ALDER_PLANKS, ALDER_STAIRS,
				ALDER_FENCE, ALDER_FENCE_GATE, ALDER_TRAPDOOR, ALDER_PRESSURE_PLATE, ALDER_BUTTON, ALDER_SIGN, ALDER_HANGING_SIGN, ALDER_SHELF,
				ALDER_SAPLING,
				
				APPLE_LOG, APPLE_WOOD, STRIPPED_APPLE_LOG, STRIPPED_APPLE_WOOD, APPLE_PLANKS, APPLE_STAIRS,
				APPLE_FENCE, APPLE_FENCE_GATE, APPLE_TRAPDOOR, APPLE_PRESSURE_PLATE, APPLE_BUTTON, APPLE_SIGN, APPLE_HANGING_SIGN, APPLE_SHELF,
				APPLE_SAPLING,
				
				ASPEN_LOG, ASPEN_WOOD, STRIPPED_ASPEN_LOG, STRIPPED_ASPEN_WOOD, ASPEN_PLANKS, ASPEN_STAIRS,
				ASPEN_FENCE, ASPEN_FENCE_GATE, ASPEN_TRAPDOOR, ASPEN_PRESSURE_PLATE, ASPEN_BUTTON, ASPEN_SIGN, ASPEN_HANGING_SIGN, ASPEN_SHELF,
				ASPEN_SAPLING,
				
				BAOBAB_LOG, BAOBAB_WOOD, STRIPPED_BAOBAB_LOG, STRIPPED_BAOBAB_WOOD, BAOBAB_PLANKS, BAOBAB_STAIRS,
				BAOBAB_FENCE, BAOBAB_FENCE_GATE, BAOBAB_TRAPDOOR, BAOBAB_PRESSURE_PLATE, BAOBAB_BUTTON, BAOBAB_SIGN, BAOBAB_HANGING_SIGN, BAOBAB_SHELF,
				BAOBAB_SAPLING,
				
				BEECH_LOG, BEECH_WOOD, STRIPPED_BEECH_LOG, STRIPPED_BEECH_WOOD, BEECH_PLANKS, BEECH_STAIRS,
				BEECH_FENCE, BEECH_FENCE_GATE, BEECH_TRAPDOOR, BEECH_PRESSURE_PLATE, BEECH_BUTTON, BEECH_SIGN, BEECH_HANGING_SIGN, BEECH_SHELF,
				BEECH_SAPLING,
				
				CEDAR_LOG, CEDAR_WOOD, STRIPPED_CEDAR_LOG, STRIPPED_CEDAR_WOOD, CEDAR_PLANKS, CEDAR_STAIRS,
				CEDAR_FENCE, CEDAR_FENCE_GATE, CEDAR_TRAPDOOR, CEDAR_PRESSURE_PLATE, CEDAR_BUTTON, CEDAR_SIGN, CEDAR_HANGING_SIGN, CEDAR_SHELF,
				CEDAR_SAPLING,
				
				CHERRY_LOG, CHERRY_WOOD, STRIPPED_CHERRY_LOG, STRIPPED_CHERRY_WOOD, CHERRY_PLANKS, CHERRY_STAIRS,
				CHERRY_FENCE, CHERRY_FENCE_GATE, CHERRY_TRAPDOOR, CHERRY_PRESSURE_PLATE, CHERRY_BUTTON, CHERRY_SIGN, CHERRY_HANGING_SIGN, CHERRY_SHELF,
				CHERRY_SAPLING,
				
				CYPRESS_LOG, CYPRESS_WOOD, STRIPPED_CYPRESS_LOG, STRIPPED_CYPRESS_WOOD, CYPRESS_PLANKS, CYPRESS_STAIRS,
				CYPRESS_FENCE, CYPRESS_FENCE_GATE, CYPRESS_TRAPDOOR, CYPRESS_PRESSURE_PLATE, CYPRESS_BUTTON, CYPRESS_SIGN, CYPRESS_HANGING_SIGN, CYPRESS_SHELF,
				CYPRESS_SAPLING,
				
				EBONY_LOG, EBONY_WOOD, STRIPPED_EBONY_LOG, STRIPPED_EBONY_WOOD, EBONY_PLANKS, EBONY_STAIRS,
				EBONY_FENCE, EBONY_FENCE_GATE, EBONY_TRAPDOOR, EBONY_PRESSURE_PLATE, EBONY_BUTTON, EBONY_SIGN, EBONY_HANGING_SIGN, EBONY_SHELF,
				EBONY_SAPLING,
				
				ELM_LOG, ELM_WOOD, STRIPPED_ELM_LOG, STRIPPED_ELM_WOOD, ELM_PLANKS, ELM_STAIRS,
				ELM_FENCE, ELM_FENCE_GATE, ELM_TRAPDOOR, ELM_PRESSURE_PLATE, ELM_BUTTON, ELM_SIGN, ELM_HANGING_SIGN, ELM_SHELF,
				ELM_SAPLING,
				
				EUCALYPTUS_LOG, EUCALYPTUS_WOOD, STRIPPED_EUCALYPTUS_LOG, STRIPPED_EUCALYPTUS_WOOD, EUCALYPTUS_PLANKS, EUCALYPTUS_STAIRS,
				EUCALYPTUS_FENCE, EUCALYPTUS_FENCE_GATE, EUCALYPTUS_TRAPDOOR, EUCALYPTUS_PRESSURE_PLATE, EUCALYPTUS_BUTTON, EUCALYPTUS_SIGN, EUCALYPTUS_HANGING_SIGN, EUCALYPTUS_SHELF,
				EUCALYPTUS_SAPLING,
				
				FIG_LOG, FIG_WOOD, STRIPPED_FIG_LOG, STRIPPED_FIG_WOOD, FIG_PLANKS, FIG_STAIRS,
				FIG_FENCE, FIG_FENCE_GATE, FIG_TRAPDOOR, FIG_PRESSURE_PLATE, FIG_BUTTON, FIG_SIGN, FIG_HANGING_SIGN, FIG_SHELF,
				FIG_SAPLING,
				
				FIR_LOG, FIR_WOOD, STRIPPED_FIR_LOG, STRIPPED_FIR_WOOD, FIR_PLANKS, FIR_STAIRS,
				FIR_FENCE, FIR_FENCE_GATE, FIR_TRAPDOOR, FIR_PRESSURE_PLATE, FIR_BUTTON, FIR_SIGN, FIR_HANGING_SIGN, FIR_SHELF,
				FIR_SAPLING,
				
				HEMLOCK_LOG, HEMLOCK_WOOD, STRIPPED_HEMLOCK_LOG, STRIPPED_HEMLOCK_WOOD, HEMLOCK_PLANKS, HEMLOCK_STAIRS,
				HEMLOCK_FENCE, HEMLOCK_FENCE_GATE, HEMLOCK_TRAPDOOR, HEMLOCK_PRESSURE_PLATE, HEMLOCK_SIGN, HEMLOCK_HANGING_SIGN, HEMLOCK_BUTTON, HEMLOCK_SHELF,
				HEMLOCK_SAPLING,
				
				HICKORY_LOG, HICKORY_WOOD, STRIPPED_HICKORY_LOG, STRIPPED_HICKORY_WOOD, HICKORY_PLANKS, HICKORY_STAIRS,
				HICKORY_FENCE, HICKORY_FENCE_GATE, HICKORY_TRAPDOOR, HICKORY_PRESSURE_PLATE, HICKORY_BUTTON, HICKORY_SIGN, HICKORY_HANGING_SIGN, HICKORY_SHELF,
				HICKORY_SAPLING,
				
				JUNIPER_LOG, JUNIPER_WOOD, STRIPPED_JUNIPER_LOG, STRIPPED_JUNIPER_WOOD, JUNIPER_PLANKS, JUNIPER_STAIRS,
				JUNIPER_FENCE, JUNIPER_FENCE_GATE, JUNIPER_TRAPDOOR, JUNIPER_PRESSURE_PLATE, JUNIPER_BUTTON, JUNIPER_SIGN, JUNIPER_HANGING_SIGN, JUNIPER_SHELF,
				JUNIPER_SAPLING,
				
				KAPOK_LOG, KAPOK_WOOD, STRIPPED_KAPOK_LOG, STRIPPED_KAPOK_WOOD, KAPOK_PLANKS, KAPOK_STAIRS,
				KAPOK_FENCE, KAPOK_FENCE_GATE, KAPOK_TRAPDOOR, KAPOK_PRESSURE_PLATE, KAPOK_BUTTON, KAPOK_SIGN, KAPOK_HANGING_SIGN, KAPOK_SHELF,
				KAPOK_SAPLING,
				
				LARCH_LOG, LARCH_WOOD, STRIPPED_LARCH_LOG, STRIPPED_LARCH_WOOD, LARCH_PLANKS, LARCH_STAIRS,
				LARCH_FENCE, LARCH_FENCE_GATE, LARCH_TRAPDOOR, LARCH_PRESSURE_PLATE, LARCH_BUTTON, LARCH_SIGN, LARCH_HANGING_SIGN, LARCH_SHELF,
				LARCH_SAPLING,
				MAHOGANY_LOG, MAHOGANY_WOOD, STRIPPED_MAHOGANY_LOG, STRIPPED_MAHOGANY_WOOD, MAHOGANY_PLANKS, MAHOGANY_STAIRS,
				MAHOGANY_FENCE, MAHOGANY_FENCE_GATE, MAHOGANY_TRAPDOOR, MAHOGANY_PRESSURE_PLATE, MAHOGANY_BUTTON, MAHOGANY_SIGN, MAHOGANY_HANGING_SIGN, MAHOGANY_SHELF,
				MAHOGANY_SAPLING,
				
				MAPLE_LOG, MAPLE_WOOD, STRIPPED_MAPLE_LOG, STRIPPED_MAPLE_WOOD, MAPLE_PLANKS, MAPLE_STAIRS,
				MAPLE_FENCE, MAPLE_FENCE_GATE, MAPLE_TRAPDOOR, MAPLE_PRESSURE_PLATE, MAPLE_BUTTON, MAPLE_SIGN, MAPLE_HANGING_SIGN, MAPLE_SHELF,
				MAPLE_SAPLING,
				
				MESQUITE_LOG, MESQUITE_WOOD, STRIPPED_MESQUITE_LOG, STRIPPED_MESQUITE_WOOD, MESQUITE_PLANKS, MESQUITE_STAIRS,
				MESQUITE_FENCE, MESQUITE_FENCE_GATE, MESQUITE_TRAPDOOR, MESQUITE_PRESSURE_PLATE, MESQUITE_BUTTON, MESQUITE_SIGN, MESQUITE_HANGING_SIGN, MESQUITE_SHELF,
				MESQUITE_SAPLING,
				
				OLIVE_LOG, OLIVE_WOOD, STRIPPED_OLIVE_LOG, STRIPPED_OLIVE_WOOD, OLIVE_PLANKS, OLIVE_STAIRS,
				OLIVE_FENCE, OLIVE_FENCE_GATE, OLIVE_TRAPDOOR, OLIVE_PRESSURE_PLATE, OLIVE_BUTTON, OLIVE_SIGN, OLIVE_HANGING_SIGN, OLIVE_SHELF,
				OLIVE_SAPLING,
				
				PALM_LOG, PALM_WOOD, STRIPPED_PALM_LOG, STRIPPED_PALM_WOOD, PALM_PLANKS, PALM_STAIRS,
				PALM_FENCE, PALM_FENCE_GATE, PALM_TRAPDOOR, PALM_PRESSURE_PLATE, PALM_BUTTON, PALM_SIGN, PALM_HANGING_SIGN, PALM_SHELF,
				PALM_SAPLING,
				
				PALO_VERDE_LOG, PALO_VERDE_WOOD, STRIPPED_PALO_VERDE_LOG, STRIPPED_PALO_VERDE_WOOD, PALO_VERDE_PLANKS, PALO_VERDE_STAIRS,
				PALO_VERDE_FENCE, PALO_VERDE_FENCE_GATE, PALO_VERDE_TRAPDOOR, PALO_VERDE_PRESSURE_PLATE, PALO_VERDE_BUTTON, PALO_VERDE_SIGN, PALO_VERDE_HANGING_SIGN, PALO_VERDE_SHELF,
				PALO_VERDE_SAPLING,
				
				PINE_LOG, PINE_WOOD, STRIPPED_PINE_LOG, STRIPPED_PINE_WOOD, PINE_PLANKS, PINE_STAIRS,
				PINE_FENCE, PINE_FENCE_GATE, PINE_TRAPDOOR, PINE_PRESSURE_PLATE, PINE_BUTTON, PINE_SIGN, PINE_HANGING_SIGN, PINE_SHELF,
				PINE_SAPLING,
				
				REDWOOD_LOG, REDWOOD_WOOD, STRIPPED_REDWOOD_LOG, STRIPPED_REDWOOD_WOOD, REDWOOD_PLANKS, REDWOOD_STAIRS,
				REDWOOD_FENCE, REDWOOD_FENCE_GATE, REDWOOD_TRAPDOOR, REDWOOD_PRESSURE_PLATE, REDWOOD_BUTTON, REDWOOD_SIGN, REDWOOD_HANGING_SIGN, REDWOOD_SHELF,
				REDWOOD_SAPLING,
				
				SEQUOIA_LOG, SEQUOIA_WOOD, STRIPPED_SEQUOIA_LOG, STRIPPED_SEQUOIA_WOOD, SEQUOIA_PLANKS, SEQUOIA_STAIRS,
				SEQUOIA_FENCE, SEQUOIA_FENCE_GATE, SEQUOIA_TRAPDOOR, SEQUOIA_PRESSURE_PLATE, SEQUOIA_BUTTON, SEQUOIA_SIGN, SEQUOIA_HANGING_SIGN, SEQUOIA_SHELF,
				SEQUOIA_SAPLING,
				
				WILLOW_LOG, WILLOW_WOOD, STRIPPED_WILLOW_LOG, STRIPPED_WILLOW_WOOD, WILLOW_PLANKS, WILLOW_STAIRS,
				WILLOW_FENCE, WILLOW_FENCE_GATE, WILLOW_TRAPDOOR, WILLOW_PRESSURE_PLATE, WILLOW_BUTTON, WILLOW_SIGN, WILLOW_HANGING_SIGN, WILLOW_SHELF,
				WILLOW_SAPLING,
				
				WHITE_SAND, WHITE_SANDSTONE, WHITE_SANDSTONE_STAIRS, WHITE_SANDSTONE_WALL,
				SMOOTH_WHITE_SANDSTONE, SMOOTH_WHITE_SANDSTONE_STAIRS,
				CUT_WHITE_SANDSTONE,
				
				PEAT_BLOCK
		);
		
		dropSelfBlocks.forEach(this::dropSelf);
		
		List<Block> slabs = List.of(
				ALDER_SLAB, APPLE_SLAB, ASPEN_SLAB, BAOBAB_SLAB, BEECH_SLAB, CEDAR_SLAB, CHERRY_SLAB,
				CYPRESS_SLAB, EBONY_SLAB, ELM_SLAB, EUCALYPTUS_SLAB, FIG_SLAB, FIR_SLAB, HEMLOCK_SLAB,
				HICKORY_SLAB, JUNIPER_SLAB, KAPOK_SLAB, LARCH_SLAB, MAHOGANY_SLAB, MAPLE_SLAB, MESQUITE_SLAB,
				OLIVE_SLAB, PALM_SLAB, PALO_VERDE_SLAB, PINE_SLAB, REDWOOD_SLAB, SEQUOIA_SLAB, WILLOW_SLAB,
				
				WHITE_SANDSTONE_SLAB, SMOOTH_WHITE_SANDSTONE_SLAB, CUT_WHITE_SANDSTONE_SLAB,
				SNOW_BRICK_SLAB, PACKED_ICE_BRICK_SLAB
		);
		
		slabs.forEach(this::createSlabItemTable);
		
		List<Block> doors = List.of(
				ALDER_DOOR, APPLE_DOOR, ASPEN_DOOR, BAOBAB_DOOR, BEECH_DOOR, CEDAR_DOOR, CHERRY_DOOR,
				CYPRESS_DOOR, EBONY_DOOR, ELM_DOOR, EUCALYPTUS_DOOR, FIG_DOOR, FIR_DOOR, HEMLOCK_DOOR,
				HICKORY_DOOR, JUNIPER_DOOR, KAPOK_DOOR, LARCH_DOOR, MAHOGANY_DOOR, MAPLE_DOOR, MESQUITE_DOOR,
				OLIVE_DOOR, PALM_DOOR, PALO_VERDE_DOOR, PINE_DOOR, REDWOOD_DOOR, SEQUOIA_DOOR, WILLOW_DOOR
		);
		
		doors.forEach(this::createDoorTable);
		
		Map<Block, Block> leavesWithSaplings = new HashMap<>();
		
		leavesWithSaplings.put(ALDER_LEAVES, ALDER_SAPLING);
		leavesWithSaplings.put(ASPEN_LEAVES, ASPEN_SAPLING);
		leavesWithSaplings.put(BEECH_LEAVES, BEECH_SAPLING);
		leavesWithSaplings.put(CEDAR_LEAVES, CEDAR_SAPLING);
		leavesWithSaplings.put(CYPRESS_LEAVES, CYPRESS_SAPLING);
		leavesWithSaplings.put(ELM_LEAVES, ELM_SAPLING);
		leavesWithSaplings.put(EUCALYPTUS_LEAVES, EUCALYPTUS_SAPLING);
		leavesWithSaplings.put(FIR_LEAVES, FIR_SAPLING);
		leavesWithSaplings.put(HEMLOCK_LEAVES, HEMLOCK_SAPLING);
		leavesWithSaplings.put(HICKORY_LEAVES, HICKORY_SAPLING);
		leavesWithSaplings.put(JUNIPER_LEAVES, JUNIPER_SAPLING);
		leavesWithSaplings.put(KAPOK_LEAVES, KAPOK_SAPLING);
		leavesWithSaplings.put(LARCH_LEAVES, LARCH_SAPLING);
		leavesWithSaplings.put(MAHOGANY_LEAVES, MAHOGANY_SAPLING);
		leavesWithSaplings.put(MAPLE_LEAVES, MAPLE_SAPLING);
		leavesWithSaplings.put(MESQUITE_LEAVES, MESQUITE_SAPLING);
		leavesWithSaplings.put(PALM_LEAVES, PALM_SAPLING);
		leavesWithSaplings.put(PALO_VERDE_LEAVES, PALO_VERDE_SAPLING);
		leavesWithSaplings.put(PINE_LEAVES, PINE_SAPLING);
		leavesWithSaplings.put(REDWOOD_LEAVES, REDWOOD_SAPLING);
		leavesWithSaplings.put(SEQUOIA_LEAVES, SEQUOIA_SAPLING);
		leavesWithSaplings.put(WILLOW_LEAVES, WILLOW_SAPLING);
		
		leavesWithSaplings.forEach((l, s) -> createLeavesDrops(l, s, NORMAL_LEAVES_SAPLING_CHANCES));
		
		createFruitLeavesDrops(APPLE_LEAVES, APPLE_SAPLING, Items.APPLE, 1);
		createFruitLeavesDrops(BAOBAB_LEAVES, BAOBAB_SAPLING, AWRItems.BAOBAB_FRUIT, 1);
		createFruitLeavesDrops(CHERRY_LEAVES, CHERRY_SAPLING, AWRItems.CHERRY, 1, 3);
		createFruitLeavesDrops(FIG_LEAVES, FIG_SAPLING, AWRItems.FIG, 1);
		createFruitLeavesDrops(OLIVE_LEAVES, OLIVE_SAPLING, AWRItems.OLIVE, 1, 2);
		createFruitLeavesDrops(HICKORY_LEAVES, HICKORY_SAPLING, AWRItems.PECAN, 2, 3);
		createFruitLeavesDrops(EBONY_LEAVES, EBONY_SAPLING, AWRItems.PERSIMMON, 1);
		
		createSingleItemTableWithSilkTouch(PERMAFROST, DIRT);
		createShearsOrSilkTouchOnlyDrop(SHORT_FROSTED_GRASS);
		createShearsOrSilkTouchOnlyDrop(TALL_FROSTED_GRASS);
		createShearsOrSilkTouchOnlyDrop(SHORT_TUNDRA_GRASS);
		createShearsOrSilkTouchOnlyDrop(TALL_TUNDRA_GRASS);
		createShearsOrSilkTouchOnlyDrop(SHORT_PRAIRIE_GRASS);
		createShearsOrSilkTouchOnlyDrop(TALL_PRAIRIE_GRASS);
		
		createSingleItemTableWithSilkTouch(SNOW_BRICKS, Items.SNOWBALL);
		createSingleItemTableWithSilkTouch(SNOW_BRICK_STAIRS, Items.SNOWBALL);
		createSingleItemTableWithSilkTouch(SNOW_BRICK_SLAB, Items.SNOWBALL);
		createSingleItemTableWithSilkTouch(SNOW_BRICK_WALL, Items.SNOWBALL);
		
		dropWhenSilkTouch(PACKED_ICE_BRICKS);
		dropWhenSilkTouch(PACKED_ICE_BRICK_STAIRS);
		dropWhenSilkTouch(PACKED_ICE_BRICK_SLAB);
		dropWhenSilkTouch(PACKED_ICE_BRICK_WALL);
		
		createSinglePropConditionTable(CATTAIL, DoublePlantBlock.HALF, DoubleBlockHalf.LOWER);
		
		add(PEAT,
				block -> LootTable.lootTable()
						.withPool(
								LootPool.lootPool()
										.when(LootItemEntityPropertyCondition.entityPresent(LootContext.EntityTarget.THIS))
										.add(
												AlternativesEntry.alternatives(
														SnowLayerBlock.LAYERS.getPossibleValues(),
														layers -> layers == 8
																? LootItem.lootTableItem(PEAT_BLOCK)
																: LootItem.lootTableItem(PEAT)
																.apply(SetItemCountFunction.setCount(ContextIntProviders.exactly(layers)))
																.when(
																		MatchBlock.blockMatches(
																				this.blocks, block, StatePropertiesPredicate.Builder.properties().hasProperty(SnowLayerBlock.LAYERS, layers)
																		)
																)
														)
										)
						)
		);
	}
	
	private void createFruitLeavesDrops(Block leaves, Block sapling, Item fruit, int fruitCount) {
		createFruitLeavesDrops(leaves, sapling, fruit, fruitCount, fruitCount);
	}
	
	private void createFruitLeavesDrops(Block leaves, Block sapling, Item fruit, int minFruitCount, int maxFruitCount) {
		createLeavesDrops(leaves, sapling, NORMAL_LEAVES_SAPLING_CHANCES).withPool(
				LootPool.lootPool()
						.setRolls(ContextIntProviders.exactly(1))
						.when(this.doesNotHaveShearsOrSilkTouch())
						.add(
								this.applyExplosionDecay(
										leaves,
										LootItem.lootTableItem(fruit)
												.apply(
														SetItemCountFunction.setCount(ContextIntProviders.between(minFruitCount, maxFruitCount))
																.when(
																		MatchBlock.blockMatches(
																				this.blocks,
																				leaves,
																				StatePropertiesPredicate.Builder.properties()
																						.hasProperty(FruitLeavesBlock.FRUIT, true)
																		)
																)
												)
								)
						)
		);
	}
}
