package me.witherbuilder13.a_world_reimagined.datagen;

import me.witherbuilder13.a_world_reimagined.api.TranslationUtils;
import me.witherbuilder13.a_world_reimagined.entity.AWREntityTypes;
import net.fabricmc.fabric.api.datagen.v1.FabricPackOutput;
import net.fabricmc.fabric.api.datagen.v1.provider.FabricLanguageProvider;
import net.minecraft.core.HolderLookup;
import net.minecraft.resources.ResourceKey;
import net.minecraft.tags.TagKey;
import net.minecraft.world.entity.EntityType;
import net.minecraft.world.entity.vehicle.boat.ChestBoat;
import net.minecraft.world.item.Item;
import net.minecraft.world.level.biome.Biome;
import net.minecraft.world.level.block.Block;
import org.jspecify.annotations.NonNull;

import java.util.List;
import java.util.concurrent.CompletableFuture;

import static me.witherbuilder13.a_world_reimagined.item.AWRItems.*;
import static me.witherbuilder13.a_world_reimagined.tag.AWRBlockTags.SUPPORTS_SNOWY_VEGETATION;
import static me.witherbuilder13.a_world_reimagined.tag.AWRBlockTags.SUPPORTS_TUNDRA_VEGETATION;
import static me.witherbuilder13.a_world_reimagined.world.biome.AWRBiomes.*;

public class AWRLanguageProvider extends FabricLanguageProvider {
	
	protected AWRLanguageProvider(FabricPackOutput packOutput, CompletableFuture<HolderLookup.Provider> registryLookup) {
		super(packOutput, registryLookup);
	}
	
	@Override
	public void generateTranslations(HolderLookup.@NonNull Provider registryLookup, @NonNull TranslationBuilder translationBuilder) {
		
		List<Item> items = List.of(
				ALDER_LOG, ALDER_WOOD, STRIPPED_ALDER_LOG, STRIPPED_ALDER_WOOD, ALDER_PLANKS, ALDER_STAIRS, ALDER_SLAB,
				ALDER_FENCE, ALDER_FENCE_GATE, ALDER_DOOR, ALDER_TRAPDOOR, ALDER_PRESSURE_PLATE, ALDER_BUTTON, ALDER_SIGN, ALDER_HANGING_SIGN, ALDER_SHELF,
				ALDER_LEAVES, ALDER_SAPLING,
				
				APPLE_LOG, APPLE_WOOD, STRIPPED_APPLE_LOG, STRIPPED_APPLE_WOOD, APPLE_PLANKS, APPLE_STAIRS, APPLE_SLAB,
				APPLE_FENCE, APPLE_FENCE_GATE, APPLE_DOOR, APPLE_TRAPDOOR, APPLE_PRESSURE_PLATE, APPLE_BUTTON, APPLE_SIGN, APPLE_HANGING_SIGN, APPLE_SHELF,
				APPLE_LEAVES, APPLE_SAPLING,
				
				ASPEN_LOG, ASPEN_WOOD, STRIPPED_ASPEN_LOG, STRIPPED_ASPEN_WOOD, ASPEN_PLANKS, ASPEN_STAIRS, ASPEN_SLAB,
				ASPEN_FENCE, ASPEN_FENCE_GATE, ASPEN_DOOR, ASPEN_TRAPDOOR, ASPEN_PRESSURE_PLATE, ASPEN_BUTTON, ASPEN_SIGN, ASPEN_HANGING_SIGN, ASPEN_SHELF,
				ASPEN_LEAVES, ASPEN_SAPLING,
				
				BAOBAB_LOG, BAOBAB_WOOD, STRIPPED_BAOBAB_LOG, STRIPPED_BAOBAB_WOOD, BAOBAB_PLANKS, BAOBAB_STAIRS, BAOBAB_SLAB,
				BAOBAB_FENCE, BAOBAB_FENCE_GATE, BAOBAB_DOOR, BAOBAB_TRAPDOOR, BAOBAB_PRESSURE_PLATE, BAOBAB_BUTTON, BAOBAB_SIGN, BAOBAB_HANGING_SIGN, BAOBAB_SHELF,
				BAOBAB_LEAVES, BAOBAB_SAPLING,
				
				BEECH_LOG, BEECH_WOOD, STRIPPED_BEECH_LOG, STRIPPED_BEECH_WOOD, BEECH_PLANKS, BEECH_STAIRS, BEECH_SLAB,
				BEECH_FENCE, BEECH_FENCE_GATE, BEECH_DOOR, BEECH_TRAPDOOR, BEECH_PRESSURE_PLATE, BEECH_BUTTON, BEECH_SIGN, BEECH_HANGING_SIGN, BEECH_SHELF,
				BEECH_LEAVES, BEECH_SAPLING,
				
				CEDAR_LOG, CEDAR_WOOD, STRIPPED_CEDAR_LOG, STRIPPED_CEDAR_WOOD, CEDAR_PLANKS, CEDAR_STAIRS, CEDAR_SLAB, 
				CEDAR_FENCE, CEDAR_FENCE_GATE, CEDAR_DOOR, CEDAR_TRAPDOOR, CEDAR_PRESSURE_PLATE, CEDAR_BUTTON, CEDAR_SIGN, CEDAR_HANGING_SIGN, CEDAR_SHELF, 
				CEDAR_LEAVES, CEDAR_SAPLING,
				
				CHERRY_LOG, CHERRY_WOOD, STRIPPED_CHERRY_LOG, STRIPPED_CHERRY_WOOD, CHERRY_PLANKS, CHERRY_STAIRS, CHERRY_SLAB,
				CHERRY_FENCE, CHERRY_FENCE_GATE, CHERRY_DOOR, CHERRY_TRAPDOOR, CHERRY_PRESSURE_PLATE, CHERRY_BUTTON, CHERRY_SIGN, CHERRY_HANGING_SIGN, CHERRY_SHELF,
				CHERRY_LEAVES, CHERRY_SAPLING,
				
				CYPRESS_LOG, CYPRESS_WOOD, STRIPPED_CYPRESS_LOG, STRIPPED_CYPRESS_WOOD, CYPRESS_PLANKS, CYPRESS_STAIRS, CYPRESS_SLAB,
				CYPRESS_FENCE, CYPRESS_FENCE_GATE, CYPRESS_DOOR, CYPRESS_TRAPDOOR, CYPRESS_PRESSURE_PLATE, CYPRESS_BUTTON, CYPRESS_SIGN, CYPRESS_HANGING_SIGN, CYPRESS_SHELF,
				CYPRESS_LEAVES, CYPRESS_SAPLING,
				
				EBONY_LOG, EBONY_WOOD, STRIPPED_EBONY_LOG, STRIPPED_EBONY_WOOD, EBONY_PLANKS, EBONY_STAIRS, EBONY_SLAB,
				EBONY_FENCE, EBONY_FENCE_GATE, EBONY_DOOR, EBONY_TRAPDOOR, EBONY_PRESSURE_PLATE, EBONY_BUTTON, EBONY_SIGN, EBONY_HANGING_SIGN, EBONY_SHELF,
				EBONY_LEAVES, EBONY_SAPLING,
				
				ELM_LOG, ELM_WOOD, STRIPPED_ELM_LOG, STRIPPED_ELM_WOOD, ELM_PLANKS, ELM_STAIRS, ELM_SLAB,
				ELM_FENCE, ELM_FENCE_GATE, ELM_DOOR, ELM_TRAPDOOR, ELM_PRESSURE_PLATE, ELM_BUTTON, ELM_SIGN, ELM_HANGING_SIGN, ELM_SHELF,
				ELM_LEAVES, ELM_SAPLING,
				
				EUCALYPTUS_LOG, EUCALYPTUS_WOOD, STRIPPED_EUCALYPTUS_LOG, STRIPPED_EUCALYPTUS_WOOD, EUCALYPTUS_PLANKS, EUCALYPTUS_STAIRS, EUCALYPTUS_SLAB,
				EUCALYPTUS_FENCE, EUCALYPTUS_FENCE_GATE, EUCALYPTUS_DOOR, EUCALYPTUS_TRAPDOOR, EUCALYPTUS_PRESSURE_PLATE, EUCALYPTUS_BUTTON, EUCALYPTUS_SIGN, EUCALYPTUS_HANGING_SIGN, EUCALYPTUS_SHELF,
				EUCALYPTUS_LEAVES, EUCALYPTUS_SAPLING,
				
				FIG_LOG, FIG_WOOD, STRIPPED_FIG_LOG, STRIPPED_FIG_WOOD, FIG_PLANKS, FIG_STAIRS, FIG_SLAB,
				FIG_FENCE, FIG_FENCE_GATE, FIG_DOOR, FIG_TRAPDOOR, FIG_PRESSURE_PLATE, FIG_BUTTON, FIG_SIGN, FIG_HANGING_SIGN, FIG_SHELF,
				FIG_LEAVES, FIG_SAPLING,
				
				FIR_LOG, FIR_WOOD, STRIPPED_FIR_LOG, STRIPPED_FIR_WOOD, FIR_PLANKS, FIR_STAIRS, FIR_SLAB, 
				FIR_FENCE, FIR_FENCE_GATE, FIR_DOOR, FIR_TRAPDOOR, FIR_PRESSURE_PLATE, FIR_BUTTON, FIR_SIGN, FIR_HANGING_SIGN, FIR_SHELF, 
				FIR_LEAVES, FIR_SAPLING,
				
				HEMLOCK_LOG, HEMLOCK_WOOD, STRIPPED_HEMLOCK_LOG, STRIPPED_HEMLOCK_WOOD, HEMLOCK_PLANKS, HEMLOCK_STAIRS, HEMLOCK_SLAB,
				HEMLOCK_FENCE, HEMLOCK_FENCE_GATE, HEMLOCK_DOOR, HEMLOCK_TRAPDOOR, HEMLOCK_PRESSURE_PLATE, HEMLOCK_BUTTON, HEMLOCK_SIGN, HEMLOCK_HANGING_SIGN, HEMLOCK_SHELF,
				HEMLOCK_LEAVES, HEMLOCK_SAPLING,
				
				HICKORY_LOG, HICKORY_WOOD, STRIPPED_HICKORY_LOG, STRIPPED_HICKORY_WOOD, HICKORY_PLANKS, HICKORY_STAIRS, HICKORY_SLAB,
				HICKORY_FENCE, HICKORY_FENCE_GATE, HICKORY_DOOR, HICKORY_TRAPDOOR, HICKORY_PRESSURE_PLATE, HICKORY_BUTTON, HICKORY_SIGN, HICKORY_HANGING_SIGN, HICKORY_SHELF,
				HICKORY_LEAVES, HICKORY_SAPLING,
				
				JUNIPER_LOG, JUNIPER_WOOD, STRIPPED_JUNIPER_LOG, STRIPPED_JUNIPER_WOOD, JUNIPER_PLANKS, JUNIPER_STAIRS, JUNIPER_SLAB,
				JUNIPER_FENCE, JUNIPER_FENCE_GATE, JUNIPER_DOOR, JUNIPER_TRAPDOOR, JUNIPER_PRESSURE_PLATE, JUNIPER_BUTTON, JUNIPER_SIGN, JUNIPER_HANGING_SIGN, JUNIPER_SHELF,
				JUNIPER_LEAVES, JUNIPER_SAPLING,
				
				KAPOK_LOG, KAPOK_WOOD, STRIPPED_KAPOK_LOG, STRIPPED_KAPOK_WOOD, KAPOK_PLANKS, KAPOK_STAIRS, KAPOK_SLAB,
				KAPOK_FENCE, KAPOK_FENCE_GATE, KAPOK_DOOR, KAPOK_TRAPDOOR, KAPOK_PRESSURE_PLATE, KAPOK_BUTTON, KAPOK_SIGN, KAPOK_HANGING_SIGN, KAPOK_SHELF,
				KAPOK_LEAVES, KAPOK_SAPLING,
				
				LARCH_LOG, LARCH_WOOD, STRIPPED_LARCH_LOG, STRIPPED_LARCH_WOOD, LARCH_PLANKS, LARCH_STAIRS, LARCH_SLAB,
				LARCH_FENCE, LARCH_FENCE_GATE, LARCH_DOOR, LARCH_TRAPDOOR, LARCH_PRESSURE_PLATE, LARCH_BUTTON, LARCH_SIGN, LARCH_HANGING_SIGN, LARCH_SHELF,
				LARCH_LEAVES, LARCH_SAPLING,
				MAHOGANY_LOG, MAHOGANY_WOOD, STRIPPED_MAHOGANY_LOG, STRIPPED_MAHOGANY_WOOD, MAHOGANY_PLANKS, MAHOGANY_STAIRS, MAHOGANY_SLAB,
				MAHOGANY_FENCE, MAHOGANY_FENCE_GATE, MAHOGANY_DOOR, MAHOGANY_TRAPDOOR, MAHOGANY_PRESSURE_PLATE, MAHOGANY_BUTTON, MAHOGANY_SIGN, MAHOGANY_HANGING_SIGN, MAHOGANY_SHELF,
				MAHOGANY_LEAVES, MAHOGANY_SAPLING,
				
				MAPLE_LOG, MAPLE_WOOD, STRIPPED_MAPLE_LOG, STRIPPED_MAPLE_WOOD, MAPLE_PLANKS, MAPLE_STAIRS, MAPLE_SLAB,
				MAPLE_FENCE, MAPLE_FENCE_GATE, MAPLE_DOOR, MAPLE_TRAPDOOR, MAPLE_PRESSURE_PLATE, MAPLE_BUTTON, MAPLE_SIGN, MAPLE_HANGING_SIGN, MAPLE_SHELF,
				MAPLE_LEAVES, MAPLE_SAPLING,
				
				MESQUITE_LOG, MESQUITE_WOOD, STRIPPED_MESQUITE_LOG, STRIPPED_MESQUITE_WOOD, MESQUITE_PLANKS, MESQUITE_STAIRS, MESQUITE_SLAB,
				MESQUITE_FENCE, MESQUITE_FENCE_GATE, MESQUITE_DOOR, MESQUITE_TRAPDOOR, MESQUITE_PRESSURE_PLATE, MESQUITE_BUTTON, MESQUITE_SIGN, MESQUITE_HANGING_SIGN, MESQUITE_SHELF,
				MESQUITE_LEAVES, MESQUITE_SAPLING,
				
				OLIVE_LOG, OLIVE_WOOD, STRIPPED_OLIVE_LOG, STRIPPED_OLIVE_WOOD, OLIVE_PLANKS, OLIVE_STAIRS, OLIVE_SLAB,
				OLIVE_FENCE, OLIVE_FENCE_GATE, OLIVE_DOOR, OLIVE_TRAPDOOR, OLIVE_PRESSURE_PLATE, OLIVE_BUTTON, OLIVE_SIGN, OLIVE_HANGING_SIGN, OLIVE_SHELF,
				OLIVE_LEAVES, OLIVE_SAPLING,
				
				PALM_LOG, PALM_WOOD, STRIPPED_PALM_LOG, STRIPPED_PALM_WOOD, PALM_PLANKS, PALM_STAIRS, PALM_SLAB,
				PALM_FENCE, PALM_FENCE_GATE, PALM_DOOR, PALM_TRAPDOOR, PALM_PRESSURE_PLATE, PALM_BUTTON, PALM_SIGN, PALM_HANGING_SIGN, PALM_SHELF,
				PALM_LEAVES, PALM_SAPLING,
				
				PALO_VERDE_LOG, PALO_VERDE_WOOD, STRIPPED_PALO_VERDE_LOG, STRIPPED_PALO_VERDE_WOOD, PALO_VERDE_PLANKS, PALO_VERDE_STAIRS, PALO_VERDE_SLAB,
				PALO_VERDE_FENCE, PALO_VERDE_FENCE_GATE, PALO_VERDE_DOOR, PALO_VERDE_TRAPDOOR, PALO_VERDE_PRESSURE_PLATE, PALO_VERDE_BUTTON, PALO_VERDE_SIGN, PALO_VERDE_HANGING_SIGN, PALO_VERDE_SHELF,
				PALO_VERDE_LEAVES, PALO_VERDE_SAPLING,
				
				PINE_LOG, PINE_WOOD, STRIPPED_PINE_LOG, STRIPPED_PINE_WOOD, PINE_PLANKS, PINE_STAIRS, PINE_SLAB,
				PINE_FENCE, PINE_FENCE_GATE, PINE_DOOR, PINE_TRAPDOOR, PINE_PRESSURE_PLATE, PINE_BUTTON, PINE_SIGN, PINE_HANGING_SIGN, PINE_SHELF,
				PINE_LEAVES, PINE_SAPLING,
				
				REDWOOD_LOG, REDWOOD_WOOD, STRIPPED_REDWOOD_LOG, STRIPPED_REDWOOD_WOOD, REDWOOD_PLANKS, REDWOOD_STAIRS, REDWOOD_SLAB,
				REDWOOD_FENCE, REDWOOD_FENCE_GATE, REDWOOD_DOOR, REDWOOD_TRAPDOOR, REDWOOD_PRESSURE_PLATE, REDWOOD_BUTTON, REDWOOD_SIGN, REDWOOD_HANGING_SIGN, REDWOOD_SHELF,
				REDWOOD_LEAVES, REDWOOD_SAPLING,
				
				SEQUOIA_LOG, SEQUOIA_WOOD, STRIPPED_SEQUOIA_LOG, STRIPPED_SEQUOIA_WOOD, SEQUOIA_PLANKS, SEQUOIA_STAIRS, SEQUOIA_SLAB,
				SEQUOIA_FENCE, SEQUOIA_FENCE_GATE, SEQUOIA_DOOR, SEQUOIA_TRAPDOOR, SEQUOIA_PRESSURE_PLATE, SEQUOIA_BUTTON, SEQUOIA_SIGN, SEQUOIA_HANGING_SIGN, SEQUOIA_SHELF,
				SEQUOIA_LEAVES, SEQUOIA_SAPLING,
				
				WILLOW_LOG, WILLOW_WOOD, STRIPPED_WILLOW_LOG, STRIPPED_WILLOW_WOOD, WILLOW_PLANKS, WILLOW_STAIRS, WILLOW_SLAB,
				WILLOW_FENCE, WILLOW_FENCE_GATE, WILLOW_DOOR, WILLOW_TRAPDOOR, WILLOW_PRESSURE_PLATE, WILLOW_BUTTON, WILLOW_SIGN, WILLOW_HANGING_SIGN, WILLOW_SHELF,
				WILLOW_LEAVES, WILLOW_SAPLING,
				
				//' ------------------------------------------------------------------------------------------------------------------------------------------------------------------
				
				WHITE_SAND, WHITE_SANDSTONE, WHITE_SANDSTONE_STAIRS, WHITE_SANDSTONE_SLAB, WHITE_SANDSTONE_WALL, CHISELED_WHITE_SANDSTONE,
				SMOOTH_WHITE_SANDSTONE, SMOOTH_WHITE_SANDSTONE_STAIRS, SMOOTH_WHITE_SANDSTONE_SLAB, CUT_WHITE_SANDSTONE, CUT_WHITE_SANDSTONE_SLAB,
				
				SNOW_BRICKS, SNOW_BRICK_STAIRS, SNOW_BRICK_SLAB, SNOW_BRICK_WALL,
				PACKED_ICE_BRICKS, PACKED_ICE_BRICK_STAIRS, PACKED_ICE_BRICK_SLAB, PACKED_ICE_BRICK_WALL,
				
				PERMAFROST, PEAT, PEAT_BLOCK, PINECONES, QUICKSAND_BUCKET, CATTAIL,
				SHORT_PRAIRIE_GRASS, TALL_PRAIRIE_GRASS, SHORT_FROSTED_GRASS, TALL_FROSTED_GRASS, SHORT_TUNDRA_GRASS, TALL_TUNDRA_GRASS,
				
				//' ------------------------------------------------------------------------------------------------------------------------------------------------------------------
				
				ALDER_BOAT, APPLE_BOAT, ASPEN_BOAT, BAOBAB_BOAT, BEECH_BOAT, CEDAR_BOAT, CHERRY_BOAT,
				CYPRESS_BOAT, EBONY_BOAT, ELM_BOAT, EUCALYPTUS_BOAT, FIG_BOAT, FIR_BOAT, HEMLOCK_BOAT,
				HICKORY_BOAT, JUNIPER_BOAT, KAPOK_BOAT, LARCH_BOAT, MAHOGANY_BOAT, MAPLE_BOAT, MESQUITE_BOAT,
				OLIVE_BOAT, PALM_BOAT, PALO_VERDE_BOAT, PINE_BOAT, REDWOOD_BOAT, SEQUOIA_BOAT, WILLOW_BOAT
		);
		
		items.forEach(item -> translationBuilder.add(item, TranslationUtils.createItem(item)));
		
		List<ResourceKey<Biome>> biomes = List.of(
				ASPEN_GROVE,
				BOG,
				DEEP_WARM_OCEAN,
				FORESTED_SLOPES,
				GIANT_GROVE, GLACIAL_SHORE,
				OLD_GROWTH_SNOWY_TAIGA,
				PRAIRIE,
				REDWOOD_FOREST, ROCKY_GROVE,
				STEPPE,
				TUNDRA,
				WOODED_TUNDRA
		);
		
		biomes.forEach(biome -> translationBuilder.add(TranslationUtils.getBiomeTranslationKey(biome), TranslationUtils.createBiome(biome)));
		
		List<Item> chestBoatItems = List.of(
				ALDER_CHEST_BOAT, APPLE_CHEST_BOAT, ASPEN_CHEST_BOAT, BAOBAB_CHEST_BOAT, BEECH_CHEST_BOAT, CEDAR_CHEST_BOAT, CHERRY_CHEST_BOAT,
				CYPRESS_CHEST_BOAT, EBONY_CHEST_BOAT, ELM_CHEST_BOAT, EUCALYPTUS_CHEST_BOAT, FIG_CHEST_BOAT, FIR_CHEST_BOAT, HEMLOCK_CHEST_BOAT,
				HICKORY_CHEST_BOAT, JUNIPER_CHEST_BOAT, KAPOK_CHEST_BOAT, LARCH_CHEST_BOAT, MAHOGANY_CHEST_BOAT, MAPLE_CHEST_BOAT, MESQUITE_CHEST_BOAT,
				OLIVE_CHEST_BOAT, PALM_CHEST_BOAT, PALO_VERDE_CHEST_BOAT, PINE_CHEST_BOAT, REDWOOD_CHEST_BOAT, SEQUOIA_CHEST_BOAT, WILLOW_CHEST_BOAT
		);
		
		List<EntityType<ChestBoat>> chestBoatEntities = List.of(
				AWREntityTypes.ALDER_CHEST_BOAT,
				AWREntityTypes.APPLE_CHEST_BOAT,
				AWREntityTypes.ASPEN_CHEST_BOAT,
				AWREntityTypes.BAOBAB_CHEST_BOAT,
				AWREntityTypes.BEECH_CHEST_BOAT,
				AWREntityTypes.CEDAR_CHEST_BOAT,
				AWREntityTypes.CHERRY_CHEST_BOAT,
				AWREntityTypes.CYPRESS_CHEST_BOAT,
				AWREntityTypes.EBONY_CHEST_BOAT,
				AWREntityTypes.ELM_CHEST_BOAT,
				AWREntityTypes.EUCALYPTUS_CHEST_BOAT,
				AWREntityTypes.FIG_CHEST_BOAT,
				AWREntityTypes.FIR_CHEST_BOAT,
				AWREntityTypes.HEMLOCK_CHEST_BOAT,
				AWREntityTypes.HICKORY_CHEST_BOAT,
				AWREntityTypes.JUNIPER_CHEST_BOAT,
				AWREntityTypes.KAPOK_CHEST_BOAT,
				AWREntityTypes.LARCH_CHEST_BOAT,
				AWREntityTypes.MAHOGANY_CHEST_BOAT,
				AWREntityTypes.MAPLE_CHEST_BOAT,
				AWREntityTypes.MESQUITE_CHEST_BOAT,
				AWREntityTypes.OLIVE_CHEST_BOAT,
				AWREntityTypes.PALM_CHEST_BOAT,
				AWREntityTypes.PALO_VERDE_CHEST_BOAT,
				AWREntityTypes.PINE_CHEST_BOAT,
				AWREntityTypes.REDWOOD_CHEST_BOAT,
				AWREntityTypes.SEQUOIA_CHEST_BOAT,
				AWREntityTypes.WILLOW_CHEST_BOAT
		);
		
		chestBoatItems.forEach(item -> translationBuilder.add(item, TranslationUtils.createChestBoat(item)));
		chestBoatEntities.forEach(entity -> translationBuilder.add(entity, TranslationUtils.createChestBoat(entity)));
		
		List<TagKey<Block>> blockTags = List.of(
				SUPPORTS_SNOWY_VEGETATION, SUPPORTS_TUNDRA_VEGETATION
		);
		
		blockTags.forEach(blockTag -> translationBuilder.add(blockTag, TranslationUtils.create(blockTag.getTranslationKey())));
	}
}
